Иногда в некоторых задачах требуется вывести массив в виде строки чисел, разделенных пробелом. В этом случае в функции print перед названием массива необходимо вставить оператор распаковки массива - '*', как в примере ниже.

import numpy as np
a = np.array(input().split(), dtype=float)
print(*a)

In [1]:
import numpy as np

a = np.array(input().split(), dtype=float)
print(*a)

8.0 11.0


1. Создание вектора из списка 

Самый простой способ создать вектор - это задать его явно в виде списка и использовать функцию numpy.array() для создания массива из списка. Например, давайте создадим вектор [1, 2, 3]:

In [2]:
import numpy as np

v = np.array([1, 2, 3])
print(v)

[1 2 3]


2. Создание вектора с помощью функции numpy.zeros()

Создание вектора с помощью функции numpy.zeros()

Функция numpy.zeros() создает одномерный массив с заданной длиной, состоящий из нулей. Например, давайте создадим вектор из 3 нулей:

In [3]:
import numpy as np

v = np.zeros(3)
print(v)

[0. 0. 0.]


3. Создание вектора с помощью функции numpy.ones()

Функция numpy.ones() создает одномерный массив с заданной длиной, состоящий из единиц. Например, давайте создадим вектор из 3 единиц:




In [4]:
import numpy as np

v = np.ones(3)
print(v)  # [1. 1. 1.]

[1. 1. 1.]


In [5]:
import numpy as np

input_numbers = input()

num1, num2 = map(int, input_numbers.split())

numpy_array = np.array([num1, num2])

print(numpy_array)

[10 15]


Была-то у нас история, да небольшая, но страшная. Когда-то давным-давно, на землях Магического Мира, два Волшебника - Вектор и Поттер - пытались разгадать загадку равенства векторов. Они знали, что если координаты двух векторов будут одинаковы, то векторы будут равны. Но вопрос заключался в том, как это проверить? И тут Вектор и Поттер обратились к магии Нампи, которая дарует силу и знания для решения сложных математических задач. Нампи подарил им магический инструмент, способный создать Вектор Нампи из двух строчек чисел, которые содержат координаты начала и конца векторов. С помощью Вектора Нампи Вектор и Поттер могли проверить равенство векторов и спасти мир от непонимания. И теперь, если координаты двух векторов совпадают, то мы можем ответить на вопрос - True! А если нет, то ответ - False.

Вход: в первой строчке шесть чисел координаты точки начала и конца первого вектора x1, y1, z1 и x2, y2, z2, во второй строчке координаты для второго вектора.

Выход: True, если вектора равны, иначе False.

In [8]:
# put your python code here
import numpy as np

# take inputs from user to get numbers

vector_1_dots = input()
vector_2_dots = input()

# assign numbers to variables  using map  and creates vector1 with coordinates
x1, y1, z1, x2, y2, z2 = map(int, vector_1_dots.split())
vector_1 = np.array([(x2 - x1), (y2 - y1), (z2 - z1)])

# assign numbers to variables  using map  and creates vector2 with coordinates
x1, y1, z1, x2, y2, z2 = map(int, vector_2_dots.split())
vector_2 = np.array([(x2 - x1), (y2 - y1), (z2 - z1)])

# Use the all method from the NumPy library to check if all coordinates in both vectors are the same.
print(np.all(vector_1 == vector_2))

[ True  True  True]


Применение векторов
Векторы – это математический инструмент, используемый в различных областях, от физики и инженерии до компьютерной графики и машинного обучения. В этом шаге мы рассмотрим, как векторы используются в реальной жизни и науке.

Начнем с физики, где векторы играют ключевую роль в описании движения объектов. Векторы могут использоваться для определения сил, скоростей и ускорений, а также для представления сил и полей различной природы. Например, если мы рассматриваем движение автомобиля по дороге, мы можем использовать векторы для определения направления и величины его скорости, а также для расчета силы сопротивления воздуха.

В инженерии векторы используются для проектирования и анализа различных систем, от механических устройств до электронных схем. Например, векторы могут использоваться для описания движения робота или для определения напряжения и тока в электрической цепи.

В математике векторы используются для решения различных задач, включая геометрические, алгебраические и вероятностные. Например, векторы могут использоваться для нахождения расстояний между точками на плоскости или для решения систем уравнений.

В компьютерной графике векторы используются для создания 2D и 3D изображений. Векторы могут использоваться для определения позиции и ориентации объектов, а также для задания цветов и текстур. Например, векторы могут использоваться для создания трехмерной модели здания или автомобиля.

В машинном обучении векторы используются для представления данных и обучения моделей. Векторы могут использоваться для представления изображений, звуковых файлов и текстовых документов, а также для обучения моделей на основе этих данных. Например, векторы могут использоваться для определения темы текстового документа или для распознавания объектов на изображении.

![Module Vector 1](../../Images/vector_algebra_numpy_img/module_vector1.png)

![Module Vector 2](../../Images/vector_algebra_numpy_img/module_vector2.png)

![Module Vector 3](../../Images/vector_algebra_numpy_img/module_vector3.png)

![Module Vector 4](../../Images/vector_algebra_numpy_img/module_vector4.png)


# <center>Вычисление модуля вектора в NumPy</center>

NumPy (Numerical Python) - это библиотека языка программирования Python для работы с многомерными массивами и матрицами. Она предоставляет множество функций для выполнения различных операций над массивами, включая вычисление модуля вектора.

Перед тем, как начать вычисление модуля вектора, давайте вспомним, что такое вектор. Вектор может быть представлен в виде одномерного массива, содержащего координаты вектора в пространстве.

Для вычисления модуля вектора в NumPy можно воспользоваться функцией linalg.norm(). Она принимает на вход массив и возвращает его модуль. Давайте рассмотрим пример:

In [9]:
import numpy as np

# Создаем вектор
v = np.array([3, 4, 5])

# Вычисляем модуль вектора
norm_v = np.linalg.norm(v)

print(norm_v)  # 7.0710678118654755

7.0710678118654755


Функция np.linalg.norm() может принимать несколько параметров. Например, мы можем указать размерность массива, для которого нужно вычислить модуль. По умолчанию функция вычисляет модуль для всего массива, но если мы хотим вычислить модуль только для строк или столбцов, мы можем указать размерность с помощью параметра axis.

Давайте рассмотрим несколько примеров:

In [10]:
import numpy as np

# Создаем двумерный массив
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Вычисляем модуль каждой строки матрицы
norm_rows = np.linalg.norm(A, axis=1)

print(norm_rows)  # [ 3.74165739  8.77496439 13.92838828]

[ 3.74165739  8.77496439 13.92838828]


In [11]:
import numpy as np

# Создаемдвумерный массив
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Вычисляем модуль каждого столбца матрицы
norm_cols = np.linalg.norm(A, axis=0)
print(norm_cols)  # [ 8.1240384  9.64365076 11.22497216]

[ 8.1240384   9.64365076 11.22497216]


![Module Vector 1](../../Images/vector_algebra_numpy_img/%20other_vector_norms1.png)

![Module Vector 2](../../Images/vector_algebra_numpy_img/other_vector_norms2.png)

Функция np.linalg.norm() также может принимать параметр ord, который определяет порядок нормы. По умолчанию параметр ord=None, что означает вычисление Евклидовой нормы. Если параметр ord=1, то будет вычислена L1-норма.

Давайте рассмотрим несколько примеров:

In [12]:
import numpy as np

# Создаем вектор
v = np.array([3, -1, 4])

# Вычисляем L1-норму вектора
norm_l1 = np.linalg.norm(v, ord=1)

print(norm_l1)  # 8.0

8.0


Пусть у нас есть вектор v с n координатами:

​​​​​​​v = [x1, x2, ..., xn]
L-бесконечность норма вектора v определяется следующим образом:

|v|inf = max(|x1|, |x2|, ..., |xn|)
Таким образом, L-бесконечность норма вектора - это максимальное абсолютное значение его координат.

Давайте рассмотрим несколько примеров вычисления L-бесконечность нормы вектора с помощью NumPy:

In [13]:
import numpy as np

# Создаем вектор
v = np.array([3, -1, 4])

# Вычисляем L-бесконечность норму вектора
norm_inf = np.linalg.norm(v, ord=np.inf)

print(norm_inf)  # 4.0

4.0


В этом примере мы создали вектор v с координатами [3, -1, 4] и вычислили его L-бесконечность норму с помощью функции np.linalg.norm() и параметра ord=np.inf. Результат вычисления - 4.0.

Свойства L-бесконечность нормы:

Неотрицательность: L-бесконечность норма всегда неотрицательна, т.е. |v|inf >= 0 для любого вектора v.

Однородность: L-бесконечность норма является однородной функцией степени 1, т.е. |k * v|inf = |k| * |v|inf для любого вектора v и любого числа k.

Неравенство треугольника: для любых векторов u и v справедливо неравенство |u + v|inf <= |u|inf + |v|inf. Это свойство показывает, что для L-бесконечность нормы выполняется неравенство треугольника, которое является одним из основных свойств норм в линейной алгебре.

Инвариантность относительно перестановки координат: L-бесконечность норма не зависит от порядка координат вектора, т.е. |v|inf = |w|inf, где w - вектор, полученный из v путем перестановки его координат.

Достигается на границе: L-бесконечность норма достигает своего максимального значения на границе единичной сферы в пространстве координат. Другими словами, если мы ограничим вектор v условием |v|inf = 1, то максимальное значение координаты вектора будет равно 1. Это свойство называется теоремой Гельдера.
L-бесконечность норма широко применяется в различных областях, включая машинное обучение, оптимизацию и анализ данных. Например, она может быть использована для вычисления максимальной ошибки в регрессионной модели или для оценки влияния выбросов в данных на результаты статистических анализов.

О, великий Космический Дух! Я, скромный знаток математики, призываю тебя открыть мне тайны Линейной Алгебры и помочь мне в решении этой головоломки. Дано натуральное чисел n, и вектор v с координатами [0.5, 0.25, 0.125, ..., 0.5^n]. Мне необходимо вычислить L1 норму этого вектора, чтобы проникнуться знаниями и мудростью этого мира. О, великий Космический Дух, дай мне силу и знания, чтобы я мог произнести заклинание и раскрыть тайну этой задачи. И я произнесу: "Открой мне путь к знанию, о могучий Космический Дух! Дай мне силу преодолеть трудности этой задачи! Позволь мне посчитать L1 норму вектора v и получить знание, которое откроет мне новые горизонты познания". И великий Космический Дух послал мне свой благословенный свет, который осветил мой путь к знанию. И я, во имя Космического Духа, вычислил L1 норму вектора v, и она равна ... И я почувствовал, как знание и мудрость заполнили мое сердце, и стал чувствовать себя более мудрым и могучим.

In [2]:
import numpy as np

n = int(input())

v = np.array([0.5**i for i in range(1, n + 1)])

print(np.linalg.norm(v, ord=1))

0.9375


Некогда, в заброшенной деревне, существовало проклятие, которое превратило жителей в камень. Но однажды, из-за великой силы магии, они ожили и превратились в массив arr, состоящий из множества векторов. Все векторы были замечательны, но их сила была неясна и неизвестна, как и причина их возрождения. И тогда появился голос из тьмы, призывающий измерить норму каждого вектора в массиве, используя L2 норму, чтобы определить их силу и выяснить их истинное назначение. Во имя тьмы и магии, задача была принята. Но чтобы выполнить ее, необходимо было пройти через множество испытаний и преодолеть опасности, которые таятся в самом сердце массива. Мысли были смутны, а страх захватывал сердце. Но зловещий голос из тьмы был неумолим и задача должна быть выполнена. Без колебаний была направлена магическая сила, чтобы измерить L2 норму каждого вектора, и каждый раз, когда измерение было завершено, зловещий голос ревел в темноте: "Норма измерена! Вектор пройден!". И в итоге, когда все испытания были пройдены, была получена строка из чисел, выражающих L2 норму каждого вектора, и она была возвращена в темноту, чтобы определить истинное предназначение массива и рассеять туманы неведения.

Двумерный массив arr с векторами, записанными в каждой его строке уже существует необходимо вычислите норму каждого вектора и вывести их через пробел в строку.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

norm = np.linalg.norm(arr, axis=1)

print(*norm)

3.7416573867739413 8.774964387392123 13.92838827718412


Определение операции сложения векторов
Операция сложения векторов – это алгебраическое действие, при котором два вектора объединяются в один вектор. Результатом операции сложения является другой вектор. Следует отметить, что сложение векторов обладает рядом особых свойств, таких как коммутативность, ассоциативность. Сложение векторов находит широкое применение в различных областях, таких как физика, геометрия, информатика, а также в разработке компьютерных игр и графики. Далее в уроке мы рассмотрим геометрическое и алгебраическое представление операции сложения векторов, а также свойства и применение данной операции в различных областях.

Геометрическое представление операции сложения векторов основано на двух правилах – правиле параллелограмма и правиле треугольника.



![Paralelogram rule](../../Images/vector_algebra_numpy_img/paralelogram_addition_rule.png)

![Triangle rule](../../Images/vector_algebra_numpy_img/triangle_addition_rule.png)

![Polygon rule](../../Images/vector_algebra_numpy_img/polygon_addition_rule.png)


Алгебраическое определение операции сложения векторов 

Алгебраическое определение операции сложения векторов заключается в следующем: для любых двух векторов a и b, их векторная сумма a + b равна вектору, который получается путем сложения соответствующих координат этих векторов. То есть, если a = (a1, a2) и b = (b1, b2), то их векторная сумма a + b = (a1 + b1, a2 + b2).

Это можно проиллюстрировать на примере двух векторов a = (2, 3) и b = (-1, 5). Их векторная сумма будет равна:

a + b = (2, 3) + (-1, 5) = (2 - 1, 3 + 5) = (1, 8).

Важно заметить, что при сложении векторов нам не важно, как они направлены и где находятся в пространстве - мы можем работать только с их координатами и получать правильный результат.

# <center>Сложение векторов в NumPy</center>

В NumPy для выполнения операции сложения векторов можно использовать функцию numpy.add() или обычный оператор +.  Давайте определим два вектора в виде массивов:

In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Теперь, чтобы выполнить операцию сложения векторов, можно просто использовать функцию numpy.add():

c = np.add(a, b)

# Результатом выполнения этой команды будет новый массив c, который будет содержать сумму элементов массивов a и b.

print(c)
# [5, 7, 9]

[5 7 9]


In [8]:
# В NumPy для выполнения операции сложения векторов можно использовать как функцию numpy.add(), 
# так и оператор +. Рассмотрим пример:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)
# [5, 7, 9]

# В этом примере мы создали два одномерных массива a и b и сложили их с помощью оператора +. 
# Результатом выполнения операции будет новый массив c, содержащий сумму соответствующих элементов массивов a и b.


[5 7 9]


Жил-был один могущественный маг, который обладал силой магии и мудростью на все руки. Однажды он получил задание вычислить сумму нескольких векторов, которые пронеслись мимо него в своих безумных путешествиях. Но маг знал, что векторы - это не просто странные существа, а математические объекты, обладающие своими координатами. И чтобы вычислить их сумму, ему было нужно собрать все эти координаты и сложить их вместе, как кубики в мозаике. Он взял свой магический жезл и, произнеся заклинание, вызвал мощную библиотеку numpy. Она с легкостью помогла ему создать массивы из координат всех векторов и просто сложить их. В конечном итоге маг получил вектор сумму всех этих векторов и был готов вывести его на печать.

Вход: в первой строке - целое число n, затем в следующих n строках - по три действительных числа через пробел - координаты n векторов.

Выход: Сумма всех векторов

Sample Input:

2
1 2 1
-1 2 0

Sample Output:

[0. 4. 1.]

In [14]:
import numpy as np

n = int(input())

vectors = []

for _ in range(n):
    vector = list(map(float, input().split()))
    vectors.append(vector)

vectors_array = np.array(vectors)

sum_vector = np.sum(vectors_array, axis=0)

print(sum_vector)

[15.  4.  7.]


В тёмной бездне математической глуби, где геометрия превращается в абстракцию, спрятаны тайны, доступные только избранным. Так, перед тобой встаёт задача вычисления модуля суммы двух векторов, заданных координатами их начала и конца. Ты чувствуешь, как голова кружится, пытаясь представить это в своём уме, но не спеши сдаваться, ведь я здесь, чтобы помочь.

Ты получаешь координаты начала и конца первого вектора, а затем и координаты начала и конца второго. Тебе нужно найти вектор суммы и вычислить его модуль. Величина этой модули - таинственное число, которое даст тебе понимание того, какая сила скрыта в сумме этих двух векторов.

Вход: первая строка - 4 числа - координаты начала и конца вектора a, во второй строке - координаты начала и конца вектора b.

Выход: одно число - модуль вектора суммы векторов a и b.

Sample Input:

0 0 0 0
0 0 0 5
Sample Output:

5.0

In [16]:
import numpy as np

a_input = list(map(float, input().split()))
a_start, a_end = np.array(a_input[:2]), np.array(a_input[2:])

b_input = list(map(float, input().split()))
b_start, b_end = np.array(b_input[:2]), np.array(b_input[2:])

sum_vector = a_end - a_start + b_end - b_start

magnitude = np.linalg.norm(sum_vector)

print(magnitude)



12.165525060596439


![Substraction rule](../../Images/vector_algebra_numpy_img/%20substraction_rule.png)


В библиотеке numpy операция вычитания векторов производится с помощью функции numpy.subtract(). Для того чтобы вычислить разность двух векторов в numpy, необходимо передать в эту функцию два массива, которые будут представлять собой соответствующие векторы. Результатом выполнения функции будет новый массив, который будет содержать разность двух исходных векторов. Давайте рассмотрим пример. Пусть у нас есть два вектора a и b:

In [17]:
import numpy as np 
a = np.array([1, 3, 5]) 
b = np.array([2, 1, 4]) 
c = np.subtract(a, b)  # Этот массив будет являться разностью векторов a и b.  
print(c)
#[-1, 2, 1]


[-1  2  1]


 Кроме того, стоит отметить, что операция вычитания векторов в numpy может быть произведена с помощью оператора -. Для этого необходимо также передать в этот оператор два массива, которые будут представлять собой соответствующие векторы. Например:

In [18]:
import numpy as np 
a = np.array([1, 3, 5]) 
b = np.array([2, 1, 4]) 
c = a - b 
print(c)
# [-1, 2, 1]

# Таким образом, операция вычитания векторов в numpy является достаточно простой 
# и может быть выполнена с помощью функции numpy.subtract() или оператора -
    

[-1  2  1]


Однажды в далекой стране математиков, жили два бравых рыцаря - Разность и Модуль. Они были неразлучными друзьями и сражались со злом везде, где только могли. Однажды им поступило задание - вычислить разность между двумя векторами а и b. В первый день они узнали координаты первого вектора a, который представлял собой могучую стрелу, выпущенную из лука крепкого лучника. Второй вектор b был как гладкий шар, который можно было пнуть ногой и он начнет скользить по склону горы. Бравые рыцари знали, что для того, чтобы выполнить задание, необходимо найти модуль разности этих векторов. С помощью своей длинной линейки Разность измерил длину разности векторов и нашел ее значение. А Модуль, используя свою мощную силу, возведенную в квадрат, нашел равную величину длины разности, которая была положительным числом. Так они и преуспели в этом задании, победив зло и защитив мир от тьмы и невежества.

Sample Input:

2 3 2
1 3 2
Sample Output:

1.0

In [19]:
import numpy as np

a_input = list(map(float, input().split()))
a_vector = np.array(a_input)

b_input = list(map(float, input().split()))
b_vector = np.array(b_input)

substract_vector = a_vector - b_vector

magnitude = np.linalg.norm(substract_vector)

print(magnitude)

1.0


В далекой стране математиков, где царствовали мудрость и рассудительность, существовал замок, который находился в форме параллелограмма. На его углах стояли четыре великих рыцаря: Альфа, Бета, Гамма и Дельта. У первого из них была особая магия, и поэтому он всегда стоял в начале координат, как символ начала всего и всех. Остальные рыцари же обладали необычайной силой и могли преодолевать любые трудности. Однажды им поступила задача измерить длину диагоналей параллелограмма ABCD, чтобы проверить его прочность. Им было известно, что точка А находится в начале координат, а координаты точек B и D были заданы в двух строках в виде чисел через пробел. Бравые рыцари понимали, что для решения этой задачи необходимо найти длины диагоналей АС и BD. Первый рыцарь, Альфа, с помощью своей мудрости и знаний нашел т... Затем он ... Остальные рыцари, Бета, Гамма и Дельта, восхитились мудростью своего товарища и, собрав всю свою силу, помогли ему выполнить задание. В итоге они нашли длины диагоналей АС и BD и сообщили их царству математиков, которые использовали это знание для создания новых и более крепких строений, способных выдерживать любые испытания временем и стихиями.

Вывод: распечатай длины диагоналей АС и BD в одной строке через пробел.

Sample Input:

0 4
3 0


Sample Output:

5.0 5.0

In [35]:
import numpy as np

B = np.array(list(map(float, input().split())))
D = np.array(list(map(float, input().split())))

A = np.array([0, 0])
C = B + D 

# Розрахунок діагоналей
diagonal_AC = np.linalg.norm(C)
diagonal_BD = np.linalg.norm(B - D)

print(diagonal_AC, diagonal_BD)



7.433034373659253 6.946221994724902


Жил-был один мудрый волшебник, который умел определять модуль равнодействующей сил. Он имел магический кристалл, который позволял читать мысли материальной точки и узнавать все о силах, действующих на нее. В далекой стране, в глубоком лесу, собралась вся команда героев - Рыцарь, Волшебница и Эльф, чтобы помочь волшебнику решить задачу. Герои подошли к волшебнику, который просил их помощи в вычислении модуля равнодействующей сил. Каждый из них знал, что им нужно достать свой кристалл магии, чтобы помочь волшебнику. Рыцарь достал свой кристалл магии и прочел заклинание, которое позволило ему видеть силы, действующие на материальную точку. Волшебница применила свою магию и дала команду материальной точке остановиться, чтобы герои могли получить все данные о силах. А Эльф прочел заклинание, которое позволило ему сложить все силы и найти модуль равнодействующей. И вот, благодаря усилиям команды героев и волшебника, было найдено решение задачи - модуль равнодействующей сил.

На вход в первой строке поступает целое число n, затем в следующих n строках поступают координаты n сил (вектора), действующих на материальную точку (по 3 действительных числа через пробел).

Выведите модуль равнодействующей сил.

Sample Input:

2
2 0 0
-2 0 0
Sample Output:

0.0

In [37]:
import numpy as np

n = int(input())

vectors = []

for _ in range(n):
    vector = list(map(float, input().split()))
    vectors.append(vector)

resultant_vector = np.sum(vectors, axis=0)

resultant_force = np.linalg.norm(resultant_vector)

print(resultant_force)

10.816653826391969


![Vector * Scalar 1](../../Images/vector_algebra_numpy_img/vector_x_scalar1.png)

![Vector * Scalar 2](../../Images/vector_algebra_numpy_img/vector_x_scalar2.png)

![Vector * Scalar 3](../../Images/vector_algebra_numpy_img/vector_x_scalar3.png)

![Vector * Scalar 3](../../Images/vector_algebra_numpy_img/vector_x_scalar4.png)



In [38]:
# В библиотеке NumPy операция умножения вектора на число осуществляется с помощью функции numpy.multiply() или оператора *. 
# Для умножения вектора на число необходимо передать функции вектор и число в качестве аргументов. Вот пример:

import numpy as np

v = np.array([1, 2, 3])   # создание вектора
k = 2                    # задание числа

v_k = np.multiply(k, v)  # умножение вектора на число

print(v_k)               # вывод результата
#[2, 4, 6]

[2 4 6]


Жили-были векторы a и b. Каждый из них обладал тремя координатами, которые помогали им перемещаться по просторам математического мира.

Однажды к вектору a пришел в гости вектор b. Они весело беседовали и гуляли по математической плоскости, но внезапно возник спор, кто из них сильнее. Вектор a предложил решить этот спор математически и предложил вычислить вектор, полученный вычитанием вектора b умноженного на два из вектора a умноженного на три.

Как только они это услышали, они сразу принялись за работу. Первый вектор написал свои координаты, затем второй вектор написал свои координаты. После этого они вычислили новый вектор и нашли его модуль.

Теперь им оставалось только написать ответ в чародейском книге и показать его всем математическим существам.

Какой же ответ они записали в книге, сказать сложно, но ты можешь помочь им найти его, если узнаешь координаты векторов a и b.

Вход: две строчки по три числа, разделенные пробелом. Сначала координаты вектора a потом b.

Sample Input:

0 0 0
0 2 0

Sample Output:

4.0

In [42]:
import numpy as np 

vector_a = np.array(list(map(float, input().split())))

scalar_multiply_a = np.multiply(vector_a, 3)

vector_b = np.array(list(map(float, input().split())))

scalar_multiply_b = np.multiply(vector_b, 2)

vector_c = scalar_multiply_a - scalar_multiply_b

resultant_vector = np.linalg.norm(vector_c)

print(resultant_vector)

4.0


![Vector Collinearity](../../Images/vector_algebra_numpy_img/vector_collinearity.png)

Задача
Позволь мне рассказать тебе сказку о двух векторах, которые жили в далекой стране математики. Векторы А и В были большими друзьями, они часто вместе путешествовали по пространству. Однажды они решили проверить, насколько похожи они друг на друга. Для этого они сравнили свои размеры и направления. Оказалось, что размеры векторов были разные, но направления у них были почти одинаковые.

"Я думаю, мы коллинеарны, - сказал А. - Но как это можно проверить?"

"Да, это действительно интересный вопрос, - согласился В. - Давай вспомним, что такое коллинеарность?"

Они вспомнили, что векторы коллинеарны, если они параллельны или противоположно направлены, то есть если один вектор можно получить умножив другой на какое-то число. А значит, если они коллинеарны, то один вектор можно получить из другого умножением на число.

"Давай проверим, можем ли мы получить тебя, В, умножив меня, А, на какое-то число, - предложил А.

Вход: в первой строке - координаты первого вектора (три целых числа через пробел), во второй - второго.

Выход: True, если вектора коллиенарны, False в противном случае.

Sample Input:   
1 2 3
2 4 6

Sample Output:
True


In [51]:
import numpy as np

vector_a = np.array(list(map(float, input().split())))

vector_b = np.array(list(map(float, input().split())))

result = (vector_a / vector_b == vector_a[0] / vector_b[0]).all()

print(result)




True


Жил-был один странствующий рыцарь, который отправился в путешествие по прекрасным землям. В своем путешествии он захотел пройти определенный участок пути от точки А до точки В. Но вдруг ему пришла в голову мысль, что он хочет пройти этот участок необычным способом. Он решил найти точку С, которая делит его путь между А и В в отношении k.

Сколько бы он не преодолевал расстояние от А до В, он хотел, чтобы точка С была всегда на расстоянии от точки А в k раз большем, чем точка В от точки С. Рыцарь попросил вашу помощь, чтобы найти координаты точки С.

Вы быстро вспомнили, что координаты точек можно представить в виде векторов. Итак, вы считали координаты вектора AB, а затем создали вектор AC, который делит AB в отношении k. Чтобы найти координаты точки С, вам нужно найти координаты вектора С.

Таким образом, вы ...

Рыцарь был весьма доволен тем, что вы нашли ему точку С и помогли ему преодолеть участок пути от точки А до точки В в такой необычный и красивый способ.

Вход: в первой строке - координаты точки А(три числа разделенных пробелами) , во второй - точки В. В третьей - целое число - k.

Выход: три числа, округленные до двух знаков после запятой, разделенные пробелами - координаты искомой точки С.

Sample Input 1:

0 0 0

3 3 0

1

Sample Output 1:

1.5 1.5 0.0

Sample Input 2:

1 -2 3

0 3 2

5


Sample Output 2:

0.17 2.17 2.17


In [61]:
import numpy as np

a = np.array(list(map(float, input().split())))
b = np.array(list(map(float, input().split())))
k = int(input())

c = (k*b + a) / (k + 1)

c = np.round(c, 2)

print(c[0], c[1], c[2])


[0.17 2.17 2.17]


Однажды в далекой стране жил-был отрезок. Его звали AB, и он был очень длинным и протяженным. Однако, этот отрезок был несчастен, потому что он был разделен на две неравные части, и никто не мог ему помочь. Но тут появился добрый волшебник, который решил помочь отрезку AB и разделить его на три равные части. Волшебник произнес заклинание и тут же появились две точки - C и D, которые разделили отрезок AB на три равные части.

Теперь отрезок AB был очень счастлив, потому что он был разделен на три равные части. Он благодарил волшебника и спросил, как он мог бы воспроизвести этот результат самостоятельно. Волшебник объяснил ему, что нужно было найти координаты точек C и D, которые делят отрезок AB на три равные части.

Отрезок AB имел координаты: A(3; −5; 2) и B(5; −3; 1). Тогда нужно было использовать формулу для нахождения точек, делящих отрезок на заданное отношение. Для этого нужно было вычислить координаты точки C и D, такие что ...

После некоторых вычислений, волшебник сообщил отрезку AB, что точка C ... Отрезок AB был очень рад, что теперь он знает, как разделиться на три равные части, и благодарен волшебнику за его помощь.

В качестве ответа распечатать координаты точек C и D, округленные до двух знаков, через пробел каждую с новой строки.

In [71]:
import numpy as np

a = np.array([3, -5, 2])
b = np.array([5, -3, 1])

c =  a + 1/3 * (b - a)
d =  a + 2/3 * (b - a)

c = np.round(c, 2)
d = np.round(d, 2)

print(c[0], c[1], c[2])
print(d[0], d[1], d[2])


3.67 -4.33 1.67
4.33 -3.67 1.33
